ci:
    config:
        schema_version: 1
        trunk_branch: main
        triggers:
            - src/**
        environments:
            - staging
            - prod
        cli_version: v0.13.1-dryrun.49
        cli_version_sha: a6e88737fcce506c4ef7eb6340234f23a028f9ed
        state_token: ${{ secrets.CASCADE_STATE_TOKEN }}
        manifest_file: .github/manifest.yaml
        manifest_key: ci
        builds:
            - name: app
              workflow: .github/workflows/build-app.yaml
              triggers: []
            - name: sharedlib
              workflow: stablekernel/cascade-example-artifact-a/.github/workflows/build-shared.yaml@main
              triggers: []
        deploys:
            - name: app
              workflow: .github/workflows/deploy-app.yaml
              triggers: []
        external:
            - repo: stablekernel/cascade-example-artifact-a
              ref: main
              deploys:
                - name: artifact-a
                  workflow: .github/workflows/deploy-artifact-a.yaml
                  on_update:
                    deploy:
                        workflow: .github/workflows/deploy-artifact-a.yaml
            - repo: stablekernel/cascade-example-artifact-b
              ref: main
              deploys:
                - name: artifact-b
                  workflow: .github/workflows/deploy-artifact-b.yaml
                  on_update:
                    deploy:
                        workflow: .github/workflows/deploy-artifact-b.yaml
    state:
        prod: {}
        release:
            sha: 974ec0426bd7edc5b31b228bcd0f6c1c60315a98
            version: v0.1.0
            committed_at: "2026-07-09T23:44:33Z"
            committed_by: joshua-temple
        staging:
            sha: 974ec0426bd7edc5b31b228bcd0f6c1c60315a98
            version: v0.1.0-rc.0
            committed_at: "2026-07-09T23:39:03Z"
            committed_by: joshua-temple
            builds:
                sharedlib:
                    sha: 974ec0426bd7edc5b31b228bcd0f6c1c60315a98
                    artifact_id: artifact-a-974ec0426bd7edc5b31b228bcd0f6c1c60315a98
            deploys:
                app:
                    sha: 974ec0426bd7edc5b31b228bcd0f6c1c60315a98
                    deployed_at: "2026-07-09T23:39:03Z"
                    deployed_by: joshua-temple
            external:
                artifact-a:
                    repo: stablekernel/cascade-example-artifact-a
                    sha: a202607092347443827
                    version: v1.0.0
                    deployed_at: "2026-07-09T23:47:53Z"
                    deployed_by: joshua-temple
                    artifacts:
                        artifact_id: artifact-a-a202607092347443827
                artifact-b:
                    repo: stablekernel/cascade-example-artifact-b
                    sha: b2026070923480219956
                    version: v2.0.0
                    deployed_at: "2026-07-09T23:48:14Z"
                    deployed_by: joshua-temple
                    artifacts:
                        artifact_name: widget-b-b2026070923480219956
    latest_release:
        version: v0.1.0
        sha: 974ec0426bd7edc5b31b228bcd0f6c1c60315a98
        released_on: "2026-07-09T23:44:33Z"
        released_by: joshua-temple
