ci:
    config:
        schema_version: 1
        trunk_branch: main
        triggers:
            - src/**
        environments:
            - staging
            - prod
        cli_version: v0.16.3-rc.0
        cli_version_sha: 8451b21446c698ec3dff9869fbc071109e7b34de
        state_token: ${{ secrets.CASCADE_STATE_TOKEN }}
        manifest_file: .github/manifest.yaml
        manifest_key: ci
        builds:
            - name: app
              workflow: .github/workflows/build-app.yaml
              triggers: []
            - name: sharedlib
              workflow: stablekernel/cascade-example-artifact-a/.github/workflows/build-shared.yaml@main
              triggers: []
        deploys:
            - name: app
              workflow: .github/workflows/deploy-app.yaml
              triggers: []
        external:
            - repo: stablekernel/cascade-example-artifact-a
              ref: main
              deploys:
                - name: artifact-a
                  workflow: .github/workflows/deploy-artifact-a.yaml
                  on_update:
                    deploy:
                        workflow: .github/workflows/deploy-artifact-a.yaml
            - repo: stablekernel/cascade-example-artifact-b
              ref: main
              deploys:
                - name: artifact-b
                  workflow: .github/workflows/deploy-artifact-b.yaml
                  on_update:
                    deploy:
                        workflow: .github/workflows/deploy-artifact-b.yaml
    state:
        prod: {}
        release:
            sha: 6180edbfe5460b876e7f2f7cb48c131d9aac2e97
            version: v0.1.0
            committed_at: "2026-07-17T06:51:38Z"
            committed_by: joshua-temple
        staging:
            sha: 6180edbfe5460b876e7f2f7cb48c131d9aac2e97
            version: v0.1.0-rc.0
            committed_at: "2026-07-17T06:46:16Z"
            committed_by: joshua-temple
            builds:
                sharedlib:
                    sha: 6180edbfe5460b876e7f2f7cb48c131d9aac2e97
                    artifact_id: artifact-a-6180edbfe5460b876e7f2f7cb48c131d9aac2e97
            deploys:
                app:
                    sha: 6180edbfe5460b876e7f2f7cb48c131d9aac2e97
                    deployed_at: "2026-07-17T06:46:16Z"
                    deployed_by: joshua-temple
            external:
                artifact-a:
                    repo: stablekernel/cascade-example-artifact-a
                    sha: cd059787b1de3873c3e38dc3d91d5887abd06d80
                    version: v0.1.0-rc.0
                    deployed_at: "2026-07-17T06:54:48Z"
                    deployed_by: joshua-temple
                artifact-b:
                    repo: stablekernel/cascade-example-artifact-b
                    sha: 866d173c15f358b8dc9286d72c365a749f36806e
                    version: v0.1.0-rc.0
                    deployed_at: "2026-07-17T06:54:37Z"
                    deployed_by: joshua-temple
    latest_release:
        version: v0.1.0
        sha: 6180edbfe5460b876e7f2f7cb48c131d9aac2e97
        released_on: "2026-07-17T06:51:38Z"
        released_by: joshua-temple
